import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './ui/Navbar'
import Footer from './ui/Footer'
import { Toaster } from 'react-hot-toast'
import { StateContext } from '@/app/context/StateContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Bankai Store',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<StateContext>
					<Navbar />
					<Toaster />
					{children}
					<Footer />
				</StateContext>
			</body>
		</html>
	)
}
